#!/bin/sh
#####################################################################
# watchdogd: Watch Dog Timer Reset Daemon
# chkconfig: - 27 01
# description: Watch Dog Timer Reset Daemon
#
# Author: Tats Shibata
# License: http://rewse.jp/license/2011.01.txt
#
# Copyright (c) 2011, Rewse Lab. All rights reserved.
#####################################################################

PROG=/usr/local/sbin/watchdogd

. /etc/rc.d/init.d/functions

test -x $PROG || exit 0

RETVAL=0

start() {
  if [ ! -f /var/lock/sybsys/watchdogd ]; then
    echo -n $"Starting watchdogd: "
    $PROG &

    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
      touch /var/lock/subsys/watchdogd
      success
    else
      failure
    fi
    echo

    echo $! > /var/run/watchdogd.pid
  fi
  return $RETVAL
}

stop() {
  echo -n $"Stopping watchdogd: "

  PID=`cat /var/run/watchdogd.pid`
  kill $PID

  RETVAL=$?
  if [ $RETVAL -eq 0 ]; then
    rm -f /var/lock/subsys/watchdogd
    rm -f /var/run/watchdogd.pid
    success
  else
    failure
  fi
  echo
  return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    start
    ;;
  condrestart)
    if [ -f /var/lock/subsys/watchdogd ]; then
      stop
      start
    fi
    ;;
  status)
    status watchdogd
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|reload|condrestart}" >&2
    exit 1
esac

exit 0
